<?php

namespace ContainerR81OVju;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_X6nEbTiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.X6nEbTi' shared service.
     *
     * @return \App\Services\DiverUtils
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\EleveController::new()": the $diverUtils argument is type-hinted with the non-existent class or interface: "App\\Services\\DiverUtils".');
    }
}
