<?php

namespace ContainerR81OVju;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_72rFtV0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.72rFtV0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.72rFtV0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'diverUtils' => ['privates', '.errored.X6nEbTi', NULL, 'Cannot determine controller argument for "App\\Controller\\EleveController::new()": the $diverUtils argument is type-hinted with the non-existent class or interface: "App\\Services\\DiverUtils".'],
            'eleveRepository' => ['privates', 'App\\Repository\\EleveRepository', 'getEleveRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'diverUtils' => '?',
            'eleveRepository' => 'App\\Repository\\EleveRepository',
            'entityManager' => '?',
        ]);
    }
}
