<?php

namespace ContainerR81OVju;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnneepedagogique2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iwyDmqg.App\Entity\Anneepedagogique' shared service.
     *
     * @return \App\Entity\Anneepedagogique
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.iwyDmqg": it references class "App\\Entity\\Anneepedagogique" but no such service exists.');
    }
}
