<?php

namespace ContainerQuBSaSj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZodYKMkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zodYKMk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zodYKMk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AnneepedagogiqueController::delete' => ['privates', '.service_locator.0ZWZcej', 'get_ServiceLocator_0ZWZcejService', true],
            'App\\Controller\\AnneepedagogiqueController::edit' => ['privates', '.service_locator.0ZWZcej', 'get_ServiceLocator_0ZWZcejService', true],
            'App\\Controller\\AnneepedagogiqueController::index' => ['privates', '.service_locator.lG9oAsx', 'get_ServiceLocator_LG9oAsxService', true],
            'App\\Controller\\AnneepedagogiqueController::new' => ['privates', '.service_locator.Q9_L6pR', 'get_ServiceLocator_Q9L6pRService', true],
            'App\\Controller\\AnneepedagogiqueController::show' => ['privates', '.service_locator.iwyDmqg', 'get_ServiceLocator_IwyDmqgService', true],
            'App\\Controller\\EleveController::delete' => ['privates', '.service_locator.2b1SjdK', 'get_ServiceLocator_2b1SjdKService', true],
            'App\\Controller\\EleveController::edit' => ['privates', '.service_locator.2b1SjdK', 'get_ServiceLocator_2b1SjdKService', true],
            'App\\Controller\\EleveController::index' => ['privates', '.service_locator.wrlJH2a', 'get_ServiceLocator_WrlJH2aService', true],
            'App\\Controller\\EleveController::new' => ['privates', '.service_locator.QWAeSLg', 'get_ServiceLocator_QWAeSLgService', true],
            'App\\Controller\\EleveController::show' => ['privates', '.service_locator.S6Y87pf', 'get_ServiceLocator_S6Y87pfService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\AnneepedagogiqueController:delete' => ['privates', '.service_locator.0ZWZcej', 'get_ServiceLocator_0ZWZcejService', true],
            'App\\Controller\\AnneepedagogiqueController:edit' => ['privates', '.service_locator.0ZWZcej', 'get_ServiceLocator_0ZWZcejService', true],
            'App\\Controller\\AnneepedagogiqueController:index' => ['privates', '.service_locator.lG9oAsx', 'get_ServiceLocator_LG9oAsxService', true],
            'App\\Controller\\AnneepedagogiqueController:new' => ['privates', '.service_locator.Q9_L6pR', 'get_ServiceLocator_Q9L6pRService', true],
            'App\\Controller\\AnneepedagogiqueController:show' => ['privates', '.service_locator.iwyDmqg', 'get_ServiceLocator_IwyDmqgService', true],
            'App\\Controller\\EleveController:delete' => ['privates', '.service_locator.2b1SjdK', 'get_ServiceLocator_2b1SjdKService', true],
            'App\\Controller\\EleveController:edit' => ['privates', '.service_locator.2b1SjdK', 'get_ServiceLocator_2b1SjdKService', true],
            'App\\Controller\\EleveController:index' => ['privates', '.service_locator.wrlJH2a', 'get_ServiceLocator_WrlJH2aService', true],
            'App\\Controller\\EleveController:new' => ['privates', '.service_locator.QWAeSLg', 'get_ServiceLocator_QWAeSLgService', true],
            'App\\Controller\\EleveController:show' => ['privates', '.service_locator.S6Y87pf', 'get_ServiceLocator_S6Y87pfService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\AnneepedagogiqueController::delete' => '?',
            'App\\Controller\\AnneepedagogiqueController::edit' => '?',
            'App\\Controller\\AnneepedagogiqueController::index' => '?',
            'App\\Controller\\AnneepedagogiqueController::new' => '?',
            'App\\Controller\\AnneepedagogiqueController::show' => '?',
            'App\\Controller\\EleveController::delete' => '?',
            'App\\Controller\\EleveController::edit' => '?',
            'App\\Controller\\EleveController::index' => '?',
            'App\\Controller\\EleveController::new' => '?',
            'App\\Controller\\EleveController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AnneepedagogiqueController:delete' => '?',
            'App\\Controller\\AnneepedagogiqueController:edit' => '?',
            'App\\Controller\\AnneepedagogiqueController:index' => '?',
            'App\\Controller\\AnneepedagogiqueController:new' => '?',
            'App\\Controller\\AnneepedagogiqueController:show' => '?',
            'App\\Controller\\EleveController:delete' => '?',
            'App\\Controller\\EleveController:edit' => '?',
            'App\\Controller\\EleveController:index' => '?',
            'App\\Controller\\EleveController:new' => '?',
            'App\\Controller\\EleveController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
