<?php

namespace ContainerQuBSaSj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IwyDmqgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iwyDmqg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iwyDmqg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'anneepedagogique' => ['privates', '.errored..service_locator.iwyDmqg.App\\Entity\\Anneepedagogique', NULL, 'Cannot autowire service ".service_locator.iwyDmqg": it references class "App\\Entity\\Anneepedagogique" but no such service exists.'],
        ], [
            'anneepedagogique' => 'App\\Entity\\Anneepedagogique',
        ]);
    }
}
