<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIckNWj6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIckNWj6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIckNWj6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIckNWj6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIckNWj6\App_KernelDevDebugContainer([
    'container.build_hash' => 'IckNWj6',
    'container.build_id' => '8b44a456',
    'container.build_time' => 1685837307,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIckNWj6');
