<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQuBSaSj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQuBSaSj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQuBSaSj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQuBSaSj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQuBSaSj\App_KernelDevDebugContainer([
    'container.build_hash' => 'QuBSaSj',
    'container.build_id' => '9d7e832c',
    'container.build_time' => 1686310418,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQuBSaSj');
