<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR81OVju\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR81OVju/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR81OVju.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR81OVju\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR81OVju\App_KernelDevDebugContainer([
    'container.build_hash' => 'R81OVju',
    'container.build_id' => 'f30a87ec',
    'container.build_time' => 1686308931,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR81OVju');
